### ISSUE TITLE
Can you please add a LICENSE.md with an applicable Open Source license? 

### ISSUE THREAD

**Issue by mikemaccana** [salmonw/salmon-wallet-v2#26]
Heya! I saw you're intending to make Salmon open source. There's not currently a `LICENSE.md` file or a `license` field inside `package.json` - what kind of license are you going to use? 

Most big projects go with either MIT or Apache 2.

 - [Sollet is Apache 2 licensed](https://github.com/project-serum/spl-token-wallet/blob/master/LICENSE), Apache 2 meets the open source definition. 
 - [node is MIT licensed](https://github.com/nodejs/node/blob/main/LICENSE), MIT is open source because it meets the open source definition
 - [The Linux kernel is GPL 2 licensed](https://en.wikipedia.org/wiki/Linux_kernel), GPL 2 meets the open source definition
 - [Rust is Apache 2 / MIT licensed](https://github.com/rust-lang/rust/blob/master/LICENSE-MIT), Apache 2 and MIT meets the open source definition. 
 - [Solana is Apache 2 licensed](https://github.com/solana-labs/solana/blob/master/LICENSE), Apache 2 meets the open source definition.

**Comment by salmon-d** [comment]
Hi Mike, thanks a lot for your comment. 
We added GPL-3.0 License.
Regards!
